using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace CleanCode.Core.Entities;


// This class is autogenerated by scaffolding..
public partial class CleanCodeContext : DbContext
{
    public CleanCodeContext()
    {
    }

    public CleanCodeContext(DbContextOptions<CleanCodeContext> options)
        : base(options)
    {
    }
    

    // Here will be DbSets..
}
